### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_downloaded'

### ISSUE THREAD

**Issue by wolfamongus2** [Digital-Sapphire/PyUpdater#103]
The file is not being downloaded from Amazon.  I believe it returning {} because it can't find the file.  I've attached my error code as well as code.  Any ideas how I can fix this?

Error:
```
{}
{}
nothing new
Traceback (most recent call last):
  File "C:/Users/D1/Desktop/31/pyu_test.py", line 25, in <module>
    if app_update.is_downloaded():
AttributeError: 'NoneType' object has no attribute 'is_downloaded'
```

Process finished with exit code 1

I'm getting also unresolved reference client_config as well as ClientConfig is underlined when I hover.
This is for: pyu_test.py

```
from pyupdater.client import Client
from client_config import ClientConfig

APP_NAME = 'pyu_test'
APP_VERSION = '1.0'

def print_status_info(info):
    total = info.get(u'total')
    downloaded = info.get(u'downloaded')
    status = info.get(u'status')
    print (downloaded, total, status)


client = Client(ClientConfig(), refresh=True,
                        progress_hooks=[print_status_info])


app_update = client.update_check(APP_NAME, APP_VERSION)

if app_update is not None:
    app_update.download()
else:
    print("nothing new")

if app_update.is_downloaded():
    app_update.extract_overwrite()

##Client_config##

```
class ClientConfig(object):
    PUBLIC_KEY = '+WDWADADAWDADDWDW'
    APP_NAME = 'pyu_test'
    COMPANY_NAME = 'pyu_test'
    UPDATE_URLS = ['https://console.aws.amazon.com/s3/buckets/xWAXWED/?region=us-east-2&tab=overview']
    MAX_DOWNLOAD_RETRIES = 3

```

**Comment by JMSwag** [comment]
@TysonDogerz I haven't figured out the reason for the {}'s yet, but I see them and my update still happens. I'll have to investigate.

Also, you may want to update you script to something like below.

```
if app_update is not None:
    app_update.download()
    if app_update.is_downloaded():
        app_update.extract_overwrite()
else:
    print("nothing new")
```

Can you send the debug logs?

```
$ pyupdater collect-debug-info
```

**Comment by wolfamongus2** [comment]
@JMSwag 
I have been trying to get this to work with bitbucket instead as in the testing of getting this working I have used 60% of my Amazon credits.  Ouch.  Imagine if someone spammed my server or got an old exe and kept re-downloading. 


I am pretty sure bitbucket is not supported though as path is not right.  
Repo Main: https://bitbucket.org/Tysondogerz/dwaddwadaw/src
It will read: 
https://bitbucket.org/Tysondogerz/dwaddwadaw/src/keys.gz
Where as the file is actually here:
https://bitbucket.org/Tysondogerz/dwaddwadaw/raw/bf9c8ee5e8cfc4d9be0299509b6db42623704955/keys.gz

raw/bf9c8ee5e8cfc4d9be0299509b6db42623704955 is constant.  

Tried this with github too the link is a little simpler, but a /blob/master/ needs to be added which pyupdater does not do.

Directory:
https://github.com/TysonDogerz/dawdwadawdwadawda 

[Versions.gz location]
https://github.com/TysonDogerz/dawdwadawdwadawda/blob/master/versions.gz 

 Pyupdater reads: 
https://github.com/TysonDogerz/dawdwadawdwadawda/versions.gz

I like bitbucket as you have unlimited private repos and good bandwidth for updates at no cost.



Config file:

```
class ClientConfig(object):
    PUBLIC_KEY = 'None'
    APP_NAME = 'dad123'
    COMPANY_NAME = 'dad123'
    UPDATE_URLS = ['https://bitbucket.org/Tysondogerz/dwaddwadaw/src']
    MAX_DOWNLOAD_RETRIES = 3 
```
Main.py
```
#!/usr/bin/env python3
from __future__ import print_function
import time
import argparse
import os
import signal
import sys
import logging
from selenium import webdriver

logging.basicConfig(level=logging.DEBUG)

from client_config import ClientConfig
from pyupdater.client import Client, AppUpdate, LibUpdate


def check_for_update():
    client = Client(ClientConfig(), refresh=True)
    app_update = client.update_check(ClientConfig.APP_NAME, ClientConfig.APP_VERSION, channel='stable')

    if app_update is not None:  # is there a new update
        if app_update.download():  # the update download is made here
            if isinstance(app_update, AppUpdate):  # you should freeze it
                app_update.extract_restart()
                return True
            else:
                app_update.extract()
                return True
    return False


def main():
    print('Current version is ', ClientConfig.APP_VERSION)
    if check_for_update():
        print('there\'s a new update :D')
    driver = webdriver.Firefox()
    driver.get('http://stackoverflow.com')


if __name__ == "__main__":
    main()
```
 
Error log:
```
DEBUG:root:Version - 2.5.1
DEBUG:pyupdater.client:PyUpdater Version 2.5.1
Current version is  1.0
{}
DEBUG:pyupdater.client:Setting up directories...
DEBUG:pyupdater.client:Downloading key file
DEBUG:pyupdater.client.downloader:Url for request: https://bitbucket.org/Tysondogerz/dwaddwadaw/src/keys.gz
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): bitbucket.org
DEBUG:urllib3.connectionpool:https://bitbucket.org:443 "GET /Tysondogerz/dwaddwadaw/src/keys.gz HTTP/1.1" 404 27857
DEBUG:pyupdater.client.downloader:Resource URL: https://bitbucket.org/Tysondogerz/dwaddwadaw/src/keys.gz
DEBUG:pyupdater.client.downloader:Got content length of: 27857
DEBUG:pyupdater.client.downloader:Block size: 32768
DEBUG:pyupdater.client.downloader:{'total': 27857, 'downloaded': 16385, 'status': 'downloading', 'percent_complete': '58.8', 'time': '00:00'}
DEBUG:pyupdater.client.downloader:Block size: 22944
DEBUG:pyupdater.client.downloader:{'total': 27857, 'downloaded': 27857, 'status': 'downloading', 'percent_complete': '100.0', 'time': '00:00'}
DEBUG:pyupdater.client.downloader:{'total': 27857, 'downloaded': 27857, 'status': 'finished', 'percent_complete': '100.0', 'time': '00:00'}
DEBUG:pyupdater.client.downloader:Download Complete
DEBUG:pyupdater.client.downloader:No hash to verify
DEBUG:pyupdater.client:Failed to decompress gzip file
DEBUG:pyupdater.client:Version file download failed
DEBUG:pyupdater.client:Not a gzipped file (b'<!')
Traceback (most recent call last):
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\site-packages\pyupdater\client\__init__.py", line 440, in _get_key_data
    decompressed_data = _gzip_decompress(data)
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\site-packages\dsdev_utils\helpers.py", line 58, in gzip_decompress
    data = decompressed_file.read()
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\gzip.py", line 276, in read
    return self._buffer.read(size)
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<!')
{}
DEBUG:pyupdater.client:Loading version file...
DEBUG:pyupdater.client:Downloading online version file
DEBUG:pyupdater.client.downloader:Url for request: https://bitbucket.org/Tysondogerz/dwaddwadaw/src/versions.gz
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): bitbucket.org
DEBUG:urllib3.connectionpool:https://bitbucket.org:443 "GET /Tysondogerz/dwaddwadaw/src/versions.gz HTTP/1.1" 404 27853
DEBUG:pyupdater.client.downloader:Resource URL: https://bitbucket.org/Tysondogerz/dwaddwadaw/src/versions.gz
DEBUG:pyupdater.client.downloader:Got content length of: 27853
DEBUG:pyupdater.client.downloader:Block size: 32768
DEBUG:pyupdater.client.downloader:{'total': 27853, 'downloaded': 16385, 'status': 'downloading', 'percent_complete': '58.8', 'time': '00:00'}
DEBUG:pyupdater.client.downloader:Block size: 22936
DEBUG:pyupdater.client.downloader:{'total': 27853, 'downloaded': 27853, 'status': 'downloading', 'percent_complete': '100.0', 'time': '00:00'}
DEBUG:pyupdater.client.downloader:{'total': 27853, 'downloaded': 27853, 'status': 'finished', 'percent_complete': '100.0', 'time': '00:00'}
DEBUG:pyupdater.client.downloader:Download Complete
DEBUG:pyupdater.client.downloader:No hash to verify
DEBUG:pyupdater.client:Failed to decompress gzip file
DEBUG:pyupdater.client:Version file download failed
DEBUG:pyupdater.client:Not a gzipped file (b'<!')
Traceback (most recent call last):
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\site-packages\pyupdater\client\__init__.py", line 417, in _get_manifest_from_http
    decompressed_data = _gzip_decompress(data)
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\site-packages\dsdev_utils\helpers.py", line 58, in gzip_decompress
    data = decompressed_file.read()
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\gzip.py", line 276, in read
    return self._buffer.read(size)
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "C:\Users\Tyson\AppData\Local\Continuum\miniconda3\lib\gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<!')
DEBUG:dsdev_utils.paths:Changing to Directory --> C:\Users\Tyson\AppData\Local\dad123\dad123
DEBUG:pyupdater.client:Found version file on file system
DEBUG:pyupdater.client:Loaded version file from file system
DEBUG:dsdev_utils.paths:Moving back to Directory --> C:\Users\Tyson\ZNEW TO TOWN\55\66\copy easy\1\src
DEBUG:pyupdater.client:Data type: <class 'bytes'>
DEBUG:pyupdater.client:App key is None
DEBUG:pyupdater.client:Version Data:
{'latest': {'dad123': {'stable': {'win': '1.1.0.2.0'}}}, 'updates': {'dad123': {'1.0.0.2.0': {'win': {'file_hash': '04a6cc8235d6002d5c0e2b83ad4b7554573abf3b2846a69a9b8b320d669445fd', 'file_size': 25085101, 'filename': 'dad123-win-`1.0`.zip'}}, '1.1.0.2.0': {'win': {'file_hash': '9c253b320250ba29684d8a8a7fb831fe7bb38ad277d6391383ccf2ea19ffa026', 'file_size': 25077527, 'filename': 'dad123-win-`1.1`.zip'}}}}, 'signature': 'DOlVBXadSN79zxatXFO9AVsxxwa67uEFb5rFXN56WsPs4thsFBGitKI6hPsrnRDJDRHI7VWJyECrH04jiIczAA'}
DEBUG:dsdev_utils.helpers:Version str: 1.0
DEBUG:pyupdater.client:Failed version file verification
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58721/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true}}, "desiredCapabilities": {"browserName": "firefox", "acceptInsecureCerts": true}}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58721/session/e024430a-50c5-4c29-a635-fcaebade948a/url {"url": "http://stackoverflow.com", "sessionId": "e024430a-50c5-4c29-a635-fcaebade948a"}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request

```

**Comment by JMSwag** [comment]
@TysonDogerz Currently bitbucket is not supported as it would require a rewrite of the client as mention in #104 by @moscoquera.

Supported platforms include destinations which allow files to be read from the root of the domain. i.e. www.example.com/versions.gz

You can comment on #87 with suggestions for v3.
