### ISSUE TITLE
Updater deletes file folder and renders getcwd() error

### ISSUE THREAD

**Issue by eullerborges** [Digital-Sapphire/PyUpdater#110]
After building and deploying the application, upon an update, the application fails to reload, either using `extract_restart()` or `extract_overwrite()`. Specially on restart, it renders these errors:
- Shell:
~~~
./MaxPy
{}
{}
{}
(1, 1, u'downloading')
(1, 1, u'finished')
sh: 0: getcwd() failed: No such file or directory
{}
{}
Traceback (most recent call last):
  File "maxpy_apploader.py", line 1299, in <module>
  File "pyupdater/client/__init__.py", line 123, in __init__
  File "pyupdater/client/__init__.py", line 206, in init_app
  File "pyupdater/client/__init__.py", line 212, in refresh
  File "pyupdater/client/__init__.py", line 469, in _get_update_manifest
  File "pyupdater/client/__init__.py", line 381, in _get_manifest_from_disk
  File "dsdev_utils/paths.py", line 95, in __init__
OSError: [Errno 2] No such file or directory
[18633] Failed to execute script maxpy_apploader
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
~~~
- Log entries after restart:
~~~
[24/01/18 15:44:22 MainProcess DEBUG] VERSION: 1.0.15
[24/01/18 15:44:22 MainProcess DEBUG] Setting up directories...
[24/01/18 15:44:22 MainProcess DEBUG] Downloading key file
[24/01/18 15:44:22 MainProcess DEBUG] Url for request: http://127.0.0.1:5000/keys.gz
[24/01/18 15:44:22 MainProcess DEBUG] Resource URL: http://127.0.0.1:5000/keys.gz
[24/01/18 15:44:22 MainProcess DEBUG] Got content length of: 181
[24/01/18 15:44:22 MainProcess DEBUG] Block size: 360
[24/01/18 15:44:22 MainProcess DEBUG] {u'status': u'downloading', u'downloaded': 181, u'total': 181, u'percent_complete': u'100.0', u'time': u'--:--'}
[24/01/18 15:44:22 MainProcess DEBUG] {u'status': u'finished', u'downloaded': 181, u'total': 181, u'percent_complete': u'100.0', u'time': u'00:00'}
[24/01/18 15:44:22 MainProcess DEBUG] Download Complete
[24/01/18 15:44:22 MainProcess DEBUG] No hash to verify
[24/01/18 15:44:22 MainProcess DEBUG] Key file download successful
[24/01/18 15:44:22 MainProcess DEBUG] Version file download failed
[24/01/18 15:44:22 MainProcess DEBUG] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "pyupdater/client/__init__.py", line 446, in _get_key_data
  File "pyupdater/client/__init__.py", line 456, in _write_manifest_2_filesystem
  File "dsdev_utils/paths.py", line 95, in __init__
OSError: [Errno 2] No such file or directory
[24/01/18 15:44:22 MainProcess DEBUG] Loading version file...
[24/01/18 15:44:22 MainProcess DEBUG] Downloading online version file
[24/01/18 15:44:22 MainProcess DEBUG] Url for request: http://127.0.0.1:5000/versions.gz
[24/01/18 15:44:22 MainProcess DEBUG] Resource URL: http://127.0.0.1:5000/versions.gz
[24/01/18 15:44:22 MainProcess DEBUG] Got content length of: 852
[24/01/18 15:44:22 MainProcess DEBUG] Block size: 1702
[24/01/18 15:44:22 MainProcess DEBUG] {u'status': u'downloading', u'downloaded': 852, u'total': 852, u'percent_complete': u'100.0', u'time': u'--:--'}
[24/01/18 15:44:22 MainProcess DEBUG] {u'status': u'finished', u'downloaded': 852, u'total': 852, u'percent_complete': u'100.0', u'time': u'00:00'}
[24/01/18 15:44:22 MainProcess DEBUG] Download Complete
[24/01/18 15:44:22 MainProcess DEBUG] No hash to verify
[24/01/18 15:44:22 MainProcess DEBUG] Version file download successful
[24/01/18 15:44:22 MainProcess DEBUG] Version file download failed
[24/01/18 15:44:22 MainProcess DEBUG] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "pyupdater/client/__init__.py", line 425, in _get_manifest_from_http
  File "pyupdater/client/__init__.py", line 456, in _write_manifest_2_filesystem
  File "dsdev_utils/paths.py", line 95, in __init__
OSError: [Errno 2] No such file or directory
~~~
Similar errors occur on overwrite.
- Last log lines before app restart:
~~~
[24/01/18 16:27:11 MainProcess DEBUG] Download Complete
[24/01/18 16:27:11 MainProcess DEBUG] Checking file hash
[24/01/18 16:27:11 MainProcess DEBUG] Update hash: f3877879848b12a9265590129ea05d1d2f7dfd0e5be8647117cf89aa99af3187
[24/01/18 16:27:11 MainProcess DEBUG] File hash verified
[24/01/18 16:27:11 MainProcess DEBUG] Applying patches
[24/01/18 16:27:11 MainProcess DEBUG] Applied patch successfully
[24/01/18 16:27:11 MainProcess DEBUG] Writing update to disk
[24/01/18 16:27:11 MainProcess DEBUG] Wrote update file
[24/01/18 16:27:11 MainProcess DEBUG] Current Info - Filename: MaxPy-nix64-1.0.16.tar.gz
[24/01/18 16:27:11 MainProcess DEBUG] Current Info - File hash: c90e684b418fe72daa4d1046f7bdea6a7bdc9846c64bb0b3cf19253f3fd3a21f
[24/01/18 16:27:11 MainProcess DEBUG] Current Info - File size: 11826776
[24/01/18 16:27:11 MainProcess DEBUG] checking file hash match
[24/01/18 16:27:11 MainProcess DEBUG] Patch download successful
[24/01/18 16:27:11 MainProcess DEBUG] Hash for binary data: c90e684b418fe72daa4d1046f7bdea6a7bdc9846c64bb0b3cf19253f3fd3a21f
[24/01/18 16:27:11 MainProcess WARNING] Update downloaded, overwriting...
[24/01/18 16:27:11 MainProcess DEBUG] Hash for binary data: c90e684b418fe72daa4d1046f7bdea6a7bdc9846c64bb0b3cf19253f3fd3a21f
[24/01/18 16:27:11 MainProcess DEBUG] Extracting Update
[24/01/18 16:27:11 MainProcess DEBUG] Update Location:
/home/eullerborges/.local/share/MaxPy/update
[24/01/18 16:27:11 MainProcess DEBUG] Update Name: MaxPy
[24/01/18 16:27:11 MainProcess DEBUG] Current App location:

/home/eullerborges/MaxPy/MaxPy
[24/01/18 16:27:11 MainProcess DEBUG] Moving app to new location:

/home/eullerborges/MaxPy
[24/01/18 16:27:11 MainProcess DEBUG] Restarting
[24/01/18 16:27:11 MainProcess DEBUG] Current App: /home/eullerborges/MaxPy/MaxPy
~~~

**Comment by moscoquera** [comment]
did you put a "data_dir" argument?

**Comment by eullerborges** [comment]
I've now tried using the onefile mode, but still to no success. I've set the `data_dir` argument to `os.path.dirname(sys.executable)` on one folder mode, to no success. It deletes the current folder and won't even recreate it.

I've tried with onefile mode, and regardless of setting data_dir, it fails when using `extract_restart()`with the error:
~~~
Traceback (most recent call last):
  File "maxpy_apploader.py", line 1349, in <module>

  File "maxpy_apploader.py", line 983, in run_application
    key_proc_queue = mp.Queue()
  File "multiprocessing/__init__.py", line 217, in Queue
  File "/tmp/pip-build-HTmGwF/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 328, in load_module
  File "/tmp/pip-build-HTmGwF/pyinstaller/PyInstaller/loader/pyimod02_archive.py", line 364, in extract
error: Error -3 while decompressing data: incorrect header check
~~~

And when using `extract_overwrite()`, the command line parameters are not passed to the application when reloaded.

Am I missing some configuration?

**Comment by moscoquera** [comment]
`data_dir` should not be `os.path.dirname(sys.executable)` if you are using onedir mode. because that folder is your projects folder and is needs to be deleted to properly overwrite/update your app. basically, your data_dir is being deleted as usual, and then pyupdater is trying to copy nonexistent files (because pyupdater deleted them when deleted  os.path.dirname(sys.executable).

by default, if data_dir is not set, pyupdater will use the user's data folder, a folder where that user always have permissions. 

regarding the onefile mode, it's a little more worrying, but i guess something similar to onedir mode is happening. because the update file needs to be unziped. and i'm pretty sure is going to fail because a file with the same name already exists on the data_dir folder. 

plus: your lastest stacktrace doesn't show anything related to pyupdater.

try don't set the `data_dir` argument, or at least use another one outside your executable folder.

**Comment by eullerborges** [comment]
I understand. I tried both modes with `data_dir` unset as well. In fact, the errors I pointed on onefile mode happened with that option unset.
The stacktrace shows an error related to PyInstaller, it seems, but I believe it has to do with the overwriting of files.
I managed to at least get the application to update using `extract_restart` but my command line parameters are not passed again to the application on restart.

**Comment by moscoquera** [comment]
when does the last  error raise? after or before the restart? can you post the full stacktrace? look like a pyinstaller is corrupted. 

pyupdater doesn't pass any argument to the restarted instance: https://github.com/JMSwag/PyUpdater/blob/master/pyupdater/client/updates.py#L218

**Comment by eullerborges** [comment]
The last error occurs after the restart, it happens as pyinstaller is preparing to run the application. That's all the trace I get, though.

I see, I believe it's the case of issue #74, then. I'm using `extract_overwrite()` and warning the user of the need to restart. Thanks for the help!

**Comment by moscoquera** [comment]
what happens if you directly run the updated app? does it run?

**Comment by eullerborges** [comment]
It runs without a problem. All problems I've had (even the one with the directory substitution without `data_dir`) are limited to the restart of the app, which means the application successfully updates, but won't reload immediately. A second run runs the updated binary without a problem.

**Comment by moscoquera** [comment]
does it run even without arguments? how big is your app? if it  fails only
on the first restart could be a race condition.

Andres Felipe Mosquera
 http://about.me/moscoquera

**Comment by eullerborges** [comment]
Curiously, it tries to run without the arguments but the error occurs even before starting `__main__`. It does indeed look like a race condition.

**Comment by Devligue** [comment]
I had similar problem, or even more complicated. It appears that when PyUpdater restarts itself something is wrong with the cwd.

The following piece of code solved it (both for Windows and for Linux)
```python
# OS
PLATFORM = platform.system()  # -> 'Windows' / 'Linux' / 'Darwin'

# SET WORKING DIRECTORY
# This is required for the PATHS to work properly when app is frozen
if PLATFORM == 'Windows':
    cwd = os.path.dirname(os.path.abspath(sys.argv[0]))
elif PLATFORM == 'Linux':
    cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
else:
    logger.warning(('This app has not been yet '
                    'tested for platform_system={}').format(PLATFORM))
    cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
os.chdir(cwd)
```

Put it somwhere at the very begining of your code. Note that if you are on Linux you might want to modify the `cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))` so that it points to your project root directory.

**Comment by JMSwag** [comment]
Hi @eullerborges, did the solution, provided by @Devligue, work for you?

**Comment by JMSwag** [comment]
No reply from reporter.

**Comment by eullerborges** [comment]
Hi, @JMSwag I'm sorry for the late reply. I couldn't test this as I had to leave the project I was working on. I'm sorry for that.

**Comment by JMSwag** [comment]
@eullerborges No worries! Thanks for the update. Once you revisit, please reopen if you're still having issues.

**Comment by wscullen** [comment]
> I had similar problem, or even more complicated. It appears that when PyUpdater restarts itself something is wrong with the cwd.
> 
> The following piece of code solved it (both for Windows and for Linux)
> 
> ```python
> # OS
> PLATFORM = platform.system()  # -> 'Windows' / 'Linux' / 'Darwin'
> 
> # SET WORKING DIRECTORY
> # This is required for the PATHS to work properly when app is frozen
> if PLATFORM == 'Windows':
>     cwd = os.path.dirname(os.path.abspath(sys.argv[0]))
> elif PLATFORM == 'Linux':
>     cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
> else:
>     logger.warning(('This app has not been yet '
>                     'tested for platform_system={}').format(PLATFORM))
>     cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
> os.chdir(cwd)
> ```
> 
> Put it somwhere at the very begining of your code. Note that if you are on Linux you might want to modify the `cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))` so that it points to your project root directory.

Can anyone explain why this fixes the restart crash issue? I know it has something to do with the folder being deleted and the os thinking the current directory doesn't exist, but I'm way too tired right now to think critically why this works. Thank  you regardless.

**Comment by witalij-s** [comment]
The error happened to me aswell when moving to the built application folder and executing the main file like: `./main`

The following error appears:
```
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "run.py", line 5, in <module>
  File "/tmp/pip-install-yGrsYR/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "site-packages/pyupdater/__init__.py", line 49, in <module>
OSError: [Errno 2] No such file or directory
[15130] Failed to execute script run
```
But when executing the main file `./folder/main` outside the application folder, the `extract_restart()` is not throwing any errors and the application is updated, restarted and works just fine.

**Comment by Devligue** [comment]
Guys, keep in mind that the piece of code that I wrote is not a real solution but more of a hack or a workaround. I believe that the broken-current-working-dir-after-restart issue ought to be fixed within PyUpdater.

I don't work on my pyupdater project anymore but I remember that the issue only occurred when the app was frozen - which btw made it pretty hard and time consuming to debug. Is that what happens to you @witalij-s?

> @sscullen 
Can anyone explain why this fixes the restart crash issue? I know it has something to do with the folder being deleted and the os thinking the current directory doesn't exist, but I'm way too tired right now to think critically why this works.

Sorry, but my memory about it is not fresh, and, as I said, I don't work on that project anymore. As I remember it the idea behind this hack was to restore `cwd` explicitly before the PyUpdater code calls `getcwd()`. The way I did this was to log the `cwd` path at various points of the updating process and see when it disappears. Then I just came up with the code for various platforms that can determine the project's root directory based either on the file in which the code is placed, or the 0th argument that is passed when executing script.

**Comment by witalij-s** [comment]
> I don't work on my pyupdater project anymore but I remember that the issue only occurred when the app was frozen - which btw made it pretty hard and time consuming to debug. Is that what happens to you @witalij-s?

@Devligue Yes my app is also in a frozen state. 

As a workaround for now I wrote a `Start.desktop` file to start the application via click. Which then changes the current working directory after clicking and executes the binary file like the following: `sh -e -c "exec \\"\\$(dirname \\"\\$0\\")/../mainfolder/main\\"" %k`

**Comment by JMSwag** [comment]
Out of curiosity, are these apps being install to "C:\Program Files"? I myself have not run into this issue but I use appdata folders for installations.

If installing to program files is the problem, I'll have to do a deep dive one of these weekends.

**Comment by Devligue** [comment]
@JMSwag I had this problem on linux as well, so it is not specific to windows.

**Comment by byoung-work** [comment]
@Devligue Oh right! The better question would be do these path require admin rights?

**Comment by JMSwag** [comment]
Oh right! The better question would be, do the directories require admin rights?

**Comment by Devligue** [comment]
I remember having some problems with admin rights, so the answer might be - yes

**Comment by mnauf** [comment]
I am having the same issue in Ubuntu. When the app restarts itself after the update, this happens. Then I have to restart the app manually

**Comment by JMSwag** [comment]
Can anyone, having this issue, create a repo which reproduces it?

**Comment by saajidsyed** [comment]
@JMSwag [29174] Cannot open self /usr/bin/timechamp or archive /usr/bin/timechamp.pkg when running on linux after restarting the app.

![image](https://user-images.githubusercontent.com/15993320/134192796-842b14dc-c106-42ef-9ff2-72320e0ac905.png)

**Comment by JMSwag** [comment]
@saajidsyed Would you be able to provide a repository that reproduces the issue?

**Comment by saajidsyed** [comment]
> @saajidsyed Would you be able to provide a repository that reproduces the issue?

@JMSwag If you are okay can you directly connect to my system and check. I have emailed you. my mail is syedsaajid882@gmail.com
