### ISSUE TITLE
Using pyupdater for an arm executable

### ISSUE THREAD

**Issue by nedosa** [Digital-Sapphire/PyUpdater#134]
I'm using pyupdater to produce an executable on an arm docker container.

I'm giving `pyupdater build --app-version 0.9 device_agent.spec` and get an error towards the end of the process:

```
[INFO] Building EXE from out00-EXE.toc completed successfully.
206282 DEBUG: Changing to Directory --> /build/ada/ada/pyu-data/new
206283 DEBUG: Temp Name: arm
206284 DEBUG: Appname: arm
206285 DEBUG: Version: 0.9
206286 DEBUG: starting archive
206288 DEBUG: Temp file: device-agent
206289 DEBUG: Moving back to Directory --> /build/ada/ada
[Errno 2] No such file or directory: 'arm'
206291 ERROR: [Errno 2] No such file or directory: 'arm'
[ERROR] [Errno 2] No such file or directory: 'arm'
206292 DEBUG: [Errno 2] No such file or directory: 'arm'
Traceback (most recent call last):
  File "/build/ada.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 108, in main
    _real_main(args)
  File "/build/ada.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 84, in _real_main
    dispatch_command(args, pyi_args)
  File "/build/ada.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 97, in dispatch_command
    cmd(args, pyi_args)
  File "/build/ada.venv/local/lib/python2.7/site-packages/pyupdater/cli/commands.py", line 96, in _cmd_build
    builder.build()
  File "/build/ada.venv/local/lib/python2.7/site-packages/pyupdater/builder.py", line 86, in build
    self._archive(self.args, temp_name)
  File "/build/ada.venv/local/lib/python2.7/site-packages/pyupdater/builder.py", line 231, in _archive
    filename = make_archive(self.app_name, app_name, version)
  File "/build/ada.venv/local/lib/python2.7/site-packages/pyupdater/utils/__init__.py", line 273, in make_archive
    shutil.copytree(target, temp_file)
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'arm'
```

The executable is produced correctly, but I wanted to find out more about the error and what I can do to prevent it.

**Comment by JMSwag** [comment]
@nedosa  Please try with master.

**Comment by nedosa** [comment]
Thanks, @JMSwag  will do.

**Comment by JMSwag** [comment]
@nedosa NP! Please report back with your results.

**Comment by nedosa** [comment]
Sorry for the delay, I just retried with master, i.e., did a `pip install  git+https://github.com/JMSwag/PyUpdater.git@master` and got the same error unfortunately.

```
194927 DEBUG: Moving back to Directory --> /build/ada/ada
[Errno 2] No such file or directory: 'arm'
194929 ERROR: [Errno 2] No such file or directory: 'arm'
[ERROR] [Errno 2] No such file or directory: 'arm'
194930 DEBUG: [Errno 2] No such file or directory: 'arm'
Traceback (most recent call last):
  File "/build/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 108, in main
    _real_main(args)
  File "/build/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 84, in _real_main
    dispatch_command(args, pyi_args)
  File "/build/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 97, in dispatch_command
    cmd(args, pyi_args)
  File "/build/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/commands.py", line 96, in _cmd_build
    builder.build()
  File "/build/da.venv/local/lib/python2.7/site-packages/pyupdater/builder.py", line 86, in build
    self._archive(self.args, temp_name)
  File "/build/da.venv/local/lib/python2.7/site-packages/pyupdater/builder.py", line 231, in _archive
    filename = make_archive(self.app_name, app_name, version)
  File "/build/da.venv/local/lib/python2.7/site-packages/pyupdater/utils/__init__.py", line 273, in make_archive
    shutil.copytree(target, temp_file)
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'arm'
```

**Comment by nedosa** [comment]
Interestingly, I tried running `master` on an x86 AWS Ubuntu 16.04 instance and got a similar error:
```
10962 DEBUG: Changing to Directory --> /home/ubuntu/ada/ada/pyu-data/new
10963 DEBUG: Temp Name: nix64
10963 DEBUG: Appname: nix64
10963 DEBUG: Version: 0.9
10963 DEBUG: starting archive
10963 DEBUG: Temp file: device-agent
10963 DEBUG: Moving back to Directory --> /home/ubuntu/ada/ada
[Errno 2] No such file or directory: 'nix64'
10963 ERROR: [Errno 2] No such file or directory: 'nix64'
[ERROR] [Errno 2] No such file or directory: 'nix64'
10963 DEBUG: [Errno 2] No such file or directory: 'nix64'
Traceback (most recent call last):
  File "/home/ubuntu/ada/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 108, in main
    _real_main(args)
  File "/home/ubuntu/ada/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 84, in _real_main
    dispatch_command(args, pyi_args)
  File "/home/ubuntu/ada/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/__init__.py", line 97, in dispatch_command
    cmd(args, pyi_args)
  File "/home/ubuntu/ada/da.venv/local/lib/python2.7/site-packages/pyupdater/cli/commands.py", line 96, in _cmd_build
    builder.build()
  File "/home/ubuntu/ada/da.venv/local/lib/python2.7/site-packages/pyupdater/builder.py", line 86, in build
    self._archive(self.args, temp_name)
  File "/home/ubuntu/ada/da.venv/local/lib/python2.7/site-packages/pyupdater/builder.py", line 231, in _archive
    filename = make_archive(self.app_name, app_name, version)
  File "/home/ubuntu/ada/da.venv/local/lib/python2.7/site-packages/pyupdater/utils/__init__.py", line 273, in make_archive
    shutil.copytree(target, temp_file)
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'nix64'
```
with

```
(da.venv) ubuntu@pm-staging:~/ada/ada$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by nedosa** [comment]
@JMSwag , if you need me to provide additional info or run more tests, let me know.

**Comment by nedosa** [comment]
@JMSwag Today I've ran the latest master against an arm docker container and I'm still getting the `OSError: [Errno 2] No such file or directory: 'arm'`.

Any chance you could guide me in the resolution of the issue ?

Thanks a mil.

**Comment by JMSwag** [comment]
Hey @nedosa , I'll take a look

**Comment by nedosa** [comment]
Thanks!

**Comment by JMSwag** [comment]
@nedosa Can you post the contents of your spec file? What is the name of the produced executable? I'm unable to reproduce on my pi. I'm assuming the spec file was created by pyinstaller instead of pyupdater.

**Comment by nedosa** [comment]
Sure. I think I followed the PyUpdater tutorial to generate the spec file. I'm not fussy on the name of the produced executable, I've put it down as `da` for now.

```
# -*- mode: python -*-

block_cipher = None

import sys
sys.modules['FixTk'] = None


a = Analysis(['device_agent.py'],
             pathex=['/build/ada/ada', '/build/ada'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='da',
          debug=True,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
```

**Comment by JMSwag** [comment]
@nedosa The spec seems to be generated with pyinstaller. When pyupdater creates the spec file, the name of the platform is placed in the name kwarg of EXE. Please regenerate the spec file using PyUpdater, then make your edits to the generated spec file. If you are still having issues please reopen.

**Comment by nedosa** [comment]
Thanks @JMSwag for looking into this. I believe that it is an issue with the one file option. I've generated the spec file using `pyupdater make-spec device_agent.py` and ran it twice, once with the one folder option, which succeeds,  and a second time with the one file option, which fails.

See below the spec files and output for each run.

```
(da.venv) [/build/ada/ada] # uname -m
armv7l
```

```
(da.venv) [/build/ada/ada] # cat arm-one-foler.spec
# -*- mode: python -*-

block_cipher = None


a = Analysis(['/build/ada/ada/device_agent.py'],
             pathex=['/build/ada/ada', u'/build/ada/ada'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[u'/build/da.venv/local/lib/python2.7/site-packages/pyupdater/hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='arm',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='arm')
```

And this is the output: https://gist.github.com/nedosa/8289e5255ec11f5f991a7deb854be9fe

Likewise, when I modify the spec file to use one file
```
(da.venv) [/build/ada/ada] # cat arm-one-file.spec
# -*- mode: python -*-

block_cipher = None


a = Analysis(['/build/ada/ada/device_agent.py'],
             pathex=['/build/ada/ada', u'/build/ada/ada'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[u'/build/da.venv/local/lib/python2.7/site-packages/pyupdater/hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          exclude_binaries=True,
          name='arm',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True)
```

I get the following output: https://gist.github.com/nedosa/fb758702e3f2295aacbf48ac47c41589

I hope the above helps.

**Comment by JMSwag** [comment]
@nedosa NP! Is there anything in the pyu-data/new folder? Also, can you provide a minimal test script which would reproduce the issue. It’s pretty hard to debug on my end since I’m unable to reproduce the issue.

**Comment by nedosa** [comment]
Thank you @JMSwag . Interestingly, with the `arm-one-file.spec` above I get nothing in the `new` folder. With the `arm-one-foler.spec`, there is the .tar.gz file
```
# ls -l pyu-data/new/
total 7780
drwxr-xr-x 2 root root    4096 Mar 26 07:06 ./
drwxr-xr-x 5 root root    4096 Nov  9 18:57 ../
-rw-r--r-- 1 root root 7954966 Mar 26 07:06 device-agent-arm-0.9.0.tar.gz
```

Also interestingly, the following .spec (likely produced by pyinstaller, but I can't remember for sure how I created it) produces a single `da` executable that runs correctly:
```
# cat device_agent.spec
# -*- mode: python -*-

block_cipher = None

import sys
sys.modules['FixTk'] = None


a = Analysis(['device_agent.py'],
             pathex=['/build/ada/ada', '/build/ada'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[u'/build/da.venv/local/lib/python2.7/site-packages/pyupdater/hooks'],
             runtime_hooks=[],
             excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='da',
          debug=True,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
```

**Comment by JMSwag** [comment]
@nedosa Hey, I'm curious to know if you have the same issue when running pyinstaller directly?

**Comment by nedosa** [comment]
Hi @JMSwag , I've ran `pyinstaller` with 3 different spec files and none has failed. Using version `3.4` of pyinstaller:
```
(da.venv) [/build/ada/ada] # pyinstaller -v
3.4
```
Is there something more specific you want to know from running pyinstaller ?

**Comment by JMSwag** [comment]
Hey @nedosa, Not at the moment. I'll do more poking around and update if I find anything.

**Comment by JMSwag** [comment]
Seems similar to #168. Can you run the build cmd with the -k flag to see if the produced executable works as expected.

**Comment by anedos** [comment]
I was able to experiment with this again, still no joy :(
```
# pyupdater build  --pyinstaller-log-info --app-version=0.9.0 arm-one-file.spec -k
[INFO] PyUpdater 3.0.1+5.g5952c55
[INFO] Compiling...
[INFO] PyInstaller: 3.4
[INFO] Python: 2.7.13
[INFO] Platform: Linux-4.4.0-1079-aws-armv7l-with-debian-9.9
[INFO] UPX is available.
[INFO] Extending PYTHONPATH with paths
['/build/ada', '/build/ada/ada', u'/build/ada/ada']
[INFO] checking Analysis
[INFO] Building Analysis because Analysis-00.toc is non existent
[INFO] Initializing module dependency graph...
[INFO] Initializing module graph hooks...
[INFO] running Analysis Analysis-00.toc
[INFO] Caching module hooks...
[INFO] Analyzing /build/ada/ada/device_agent.py
[INFO] Processing pre-safe import module hook   _xmlplus
[INFO] Processing pre-find module path hook   distutils
[INFO] distutils: retargeting to non-venv dir '/usr/lib/python2.7/distutils'
[INFO] Processing pre-safe import module hook   win32com
[INFO] Processing pre-safe import module hook   urllib3.packages.six.moves
[INFO] Loading module hooks...
[INFO] Loading module hook "hook-distutils.py"...
[INFO] Loading module hook "hook-sysconfig.py"...
[INFO] Loading module hook "hook-appdirs.py"...
[INFO] Excluding import 'win32com'
[INFO]   Removing import of win32com from module appdirs
[INFO] Loading module hook "hook-xml.py"...
[INFO] Loading module hook "hook-xml.dom.domreg.py"...
[INFO] Loading module hook "hook-pkg_resources.py"...
[INFO] Loading module hook "hook-dsdev_utils.py"...
[INFO] Loading module hook "hook-pytz.py"...
[INFO] Loading module hook "hook-httplib.py"...
[INFO] Loading module hook "hook-certifi.py"...
[INFO] Loading module hook "hook-encodings.py"...
[INFO] Looking for ctypes DLLs
[INFO] Analyzing run-time hooks ...
[INFO] Including run-time hook 'pyi_rth_pkgres.py'
[INFO] Including run-time hook 'pyi_rth_multiprocessing.py'
[INFO] Including run-time hook 'pyi_rth_twisted.py'
[INFO] Looking for dynamic libraries
[INFO] Looking for eggs
[INFO] Python library not in binary dependencies. Doing additional searching...
[INFO] Using Python library /usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0
[INFO] Warnings written to /build/ada/ada/.pyupdater/work/arm-one-file/warn-arm-one-file.txt
[INFO] Graph cross-reference written to /build/ada/ada/.pyupdater/work/arm-one-file/xref-arm-one-file.html
[INFO] checking PYZ
[INFO] Building PYZ because PYZ-00.toc is non existent
[INFO] Building PYZ (ZlibArchive) /build/ada/ada/.pyupdater/work/arm-one-file/PYZ-00.pyz
[INFO] Building PYZ (ZlibArchive) /build/ada/ada/.pyupdater/work/arm-one-file/PYZ-00.pyz completed successfully.
[INFO] checking PKG
[INFO] Building PKG because PKG-00.toc is non existent
[INFO] Building PKG (CArchive) PKG-00.pkg
[INFO] Building PKG (CArchive) PKG-00.pkg completed successfully.
[INFO] Bootloader /build/da.venv/local/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-32bit-arm/run_d
[INFO] checking EXE
[INFO] Building EXE because EXE-00.toc is non existent
[INFO] Building EXE from EXE-00.toc
[INFO] Appending archive to ELF section in EXE /build/ada/ada/.pyupdater/work/arm-one-file/arm
[INFO] Building EXE from EXE-00.toc completed successfully.
[Errno 2] No such file or directory: 'arm'
[ERROR] [Errno 2] No such file or directory: 'arm'
```

Not only the error persists, but now the `arm` executable does not load correctly:

```
./arm
[2084] PyInstaller Bootloader 3.x
[2084] LOADER: executable is /build/ada/ada/.pyupdater/work/arm-one-file/arm
[2084] LOADER: homepath is /build/ada/ada/.pyupdater/work/arm-one-file
[2084] LOADER: _MEIPASS2 is NULL
[2084] LOADER: archivename is /build/ada/ada/.pyupdater/work/arm-one-file/arm
[2084] LOADER: Extracting binaries
[2084] LOADER: Executing self as child
[2084] LOADER: set _MEIPASS2 to /tmp/_MEIrb6WFe
[2084] LOADER: LD_LIBRARY_PATH=/tmp/_MEIrb6WFe
[2084] LOADER: Registering signal handlers
[2087] PyInstaller Bootloader 3.x
[2087] LOADER: executable is /build/ada/ada/.pyupdater/work/arm-one-file/arm
[2087] LOADER: homepath is /build/ada/ada/.pyupdater/work/arm-one-file
[2087] LOADER: _MEIPASS2 is /tmp/_MEIrb6WFe
[2087] LOADER: archivename is /build/ada/ada/.pyupdater/work/arm-one-file/arm
[2087] LOADER: Already in the child - running user's code.
[2087] LOADER: Python library: /tmp/_MEIrb6WFe/libpython2.7.so.1.0
[2087] Error loading Python lib '/tmp/_MEIrb6WFe/libpython2.7.so.1.0': dlopen: /tmp/_MEIrb6WFe/libpython2.7.so.1.0: cannot open shared object file: No such file or directory
[2084] LOADER: Restoring signal handlers
[2084] LOADER: freeing args
[2084] LOADER: returning child exit status 255
[2084] LOADER: Back to parent (RC: 255)
[2084] LOADER: Doing cleanup
[2084] LOADER: Freeing archive status for /build/ada/ada/.pyupdater/work/arm-one-file/arm
```

I've double-checked and in previous test runs, even though the build error was always there, the `arm` executable would load correctly.

**Comment by anedos** [comment]
I ran some further tests with respect to the loading error, the following .spec file loads correctly:
```
# -*- mode: python -*-

block_cipher = None

import sys
sys.modules['FixTk'] = None


a = Analysis(['device_agent.py'],
             pathex=['/build/ada/ada', '/build/ada'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[u'/build/da.venv/local/lib/python2.7/site-packages/pyupdater/hooks'],
             runtime_hooks=[],
             excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='da',
          debug=True,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
```

but this one does not:

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['/build/ada/ada/device_agent.py'],
             pathex=['/build/ada/ada', u'/build/ada/ada'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[u'/build/da.venv/local/lib/python2.7/site-packages/pyupdater/hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          exclude_binaries=True,
          name='arm',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True)
```

**Comment by anedos** [comment]
Upon further testing, adding the `exclude_binaries=True` option seems to trigger the loading issue, apologies for the confusion.

**Comment by anedos** [comment]
So after testing more permutations of the .spec file, in order to avoid the error that initially prompted this issue `[ERROR] [Errno 2] No such file or directory: 'arm'`, the `name` argument in the `exe` section _has_ to be `arm`. Any other name raises the `No such file or directory...` error.

**Comment by JMSwag** [comment]
@anedos The name attribute is important and has to be the name of the platform on which you are compiling.
