### ISSUE TITLE
Syntax error Python 3.7 - `async` keyword

### ISSUE THREAD

**Issue by JakubBlaha** [Digital-Sapphire/PyUpdater#140]
In some file of PyUpdater, there is an `async` parameter in various functions, which causes some issues in Python 3.7 version.

**Example code:**
*pyupdater.client.updates.py*
```
def download(self, async=False):
        """Downloads update

        ######Args:

            async (bool): Perform download in background thread
        """
        if async is True:
            if self._is_downloading is False:
                self._is_downloading = True
                threading.Thread(target=self._download).start()
        else:
            if self._is_downloading is False:
                self._is_downloading = True
                return self._download()
```
**Error:**
```
Traceback (most recent call last):
  File "c:/Users/jakub/Desktop/FastFastLauncher/src/main.py", line 1, in <module>
    from pyupdater.client import Client
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyupdater-2.5.3-py3.7.egg\pyupdater\client\__init__.py", line 45, in <module>
    from pyupdater.client.updates import AppUpdate, _get_highest_version, LibUpdate
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyupdater-2.5.3-py3.7.egg\pyupdater\client\updates.py", line 371
    def download(self, async=False):
                           ^
SyntaxError: invalid syntax
```

**Comment by 2press** [comment]
This has already been fixed in the current master branch. You either have to wait for the next release or upgrade to the latest commit of the master branch.

**Comment by JakubBlaha** [comment]
I am sorry, I realized this later. However I faced an issue when building. The error told something like `System could not find directory 'win'`. This happened right before the end of the build. The exe was in *deploy* folder already.
