### ISSUE TITLE
Unable to get past build step.

### ISSUE THREAD

**Issue by Zageron** [Digital-Sapphire/PyUpdater#147]
At a loss. It's a bare bones project, nothing fancy.
I've tried the nested folder, and I've tried a root directory script.

Any advice, or do you need more context?

```
$ pyupdater make-spec --app-version 0.0.1 r3-launcher/r3-launcher.py
[INFO] PyUpdater 2.5.3+43.g8f4f921
[INFO] wrote F:\git\nuffr\r3-launcher\win.spec
```

```
$ pyupdater build --app-version 0.0.1 win.spec
[INFO] PyUpdater 2.5.3+43.g8f4f921
[INFO] PyInstaller: 3.1
[INFO] Python: 3.7.2
[INFO] Platform: Windows-10-10.0.17763-SP0
[INFO] UPX is not available.
[INFO] Extending PYTHONPATH with paths
['F:\\git\\nuffr\\r3-launcher',
 'F:\\git\\nuffr\\r3-launcher',
 'F:\\git\\nuffr\\r3-launcher']
[INFO] checking Analysis
[INFO] Building Analysis because out00-Analysis.toc is non existent
[INFO] Initializing module dependency graph...
[INFO] Initializing module graph hooks...
[INFO] Analyzing base_library.zip ...
[ERROR] tuple index out of range
tuple index out of range
```

Spec
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['F:\\git\\nuffr\\r3-launcher\\r3-launcher\\r3-launcher.py'],
             pathex=['F:\\git\\nuffr\\r3-launcher', 'F:\\git\\nuffr\\r3-launcher'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=['f:\\git\\pyupdater\\pyupdater\\hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='win',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='win')
```

**Comment by JMSwag** [comment]
@Zageron Does it build when using pyinstaller directly?

**Comment by Zageron** [comment]
Nope.
```
$ pyinstaller r3-launcher.py
56 INFO: PyInstaller: 3.1
56 INFO: Python: 3.7.2
56 INFO: Platform: Windows-10-10.0.17763-SP0
58 INFO: wrote F:\git\nuffr\r3-launcher\r3-launcher.spec
59 INFO: UPX is not available.
61 INFO: Extending PYTHONPATH with paths
['F:\\git\\nuffr\\r3-launcher', 'F:\\git\\nuffr\\r3-launcher']
61 INFO: checking Analysis
61 INFO: Building Analysis because out00-Analysis.toc is non existent
61 INFO: Initializing module dependency graph...
64 INFO: Initializing module graph hooks...
65 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "C:\Users\erane\AppData\Local\Programs\Python\Python37\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.1', 'console_scripts', 'pyinstaller')()
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
    self.assemble()
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 552, in initialize_modgraph
    graph.import_hook(m)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 900, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 984, in _find_head_package
    q = self._safe_import_module(head, qname, parent)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1205, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1289, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1454, in _scan_code
    self._scan_bytecode_stores(co, m)
  File "c:\users\erane\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1499, in _scan_bytecode_stores
    name = co.co_names[oparg]
IndexError: tuple index out of range
```

**Comment by Zageron** [comment]
Looks like pyinstaller doesn't support python 3.7+. So I installed the git+https://github.com/pyinstaller/pyinstaller.git version and it all works.

Thanks for the tip, should have thought of that. Last night was frustrating.

**Comment by JMSwag** [comment]
@Zageron The async keyword has been removed from PyUpdater allowing usage with py37  😉

**Comment by Zageron** [comment]
Thanks!

**Comment by JMSwag** [comment]
@Zageron NP!
