### ISSUE TITLE
`version_meta` becomes empty in config, cryptic errors

### ISSUE THREAD

**Issue by grandrew** [Digital-Sapphire/PyUpdater#217]
```
[ERROR] pyupdater.cli 87: 'updates'
[DEBUG] pyupdater.cli 88: 'updates'
Traceback (most recent call last):
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/cli/__init__.py", line 79, in main
    _real_main(args)
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/cli/__init__.py", line 55, in _real_main
    dispatch_command(args, pyi_args)
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/cli/__init__.py", line 68, in dispatch_command
    cmd(args, pyi_args)
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/cli/commands.py", line 305, in _cmd_pkg
    pyu.process_packages(ns.verbose)
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/core/__init__.py", line 77, in process_packages
    self.ph.process_packages(report_errors)
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/core/package_handler/__init__.py", line 107, in process_packages
    pkg_manifest, patch_manifest = self._get_package_list(report_errors)
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/core/package_handler/__init__.py", line 191, in _get_package_list
    PackageHandler._update_file_list(self.version_data, new_pkg)
  File "/home/vasily/environment-name/artemm/grandrew/-val/.tox/pyupdater/lib/python3.7/site-packages/pyupdater/core/package_handler/__init__.py", line 293, in _update_file_list
    files = json_data[settings.UPDATES_KEY]
KeyError: 'updates'
```

the symptoms is that it toes not upload anything without any particular error

the solution is to delete `version_meta` from config file

**Comment by JMSwag** [comment]
The PyUpdater config file should not be updated by hand.
