### ISSUE TITLE
Update fails due to failing key length check

### ISSUE THREAD

**Issue by cbenhagen** [Digital-Sapphire/PyUpdater#24]
``` python
Traceback (most recent call last):
  File "foo.py", line 30, in <module>
    client = Client(ClientConfig(), refresh=True)
  File "pyupdater/client/__init__.py", line 150, in __init__
  File "pyupdater/client/__init__.py", line 228, in init_app
  File "pyupdater/client/__init__.py", line 232, in refresh
  File "pyupdater/client/__init__.py", line 354, in _get_signing_key
  File "ed25519/keys.py", line 142, in __init__
AssertionError
```

PyUpdater version 2.1.4+14.geb460aa
Python 2.7.12
macOS Sierra

**Comment by Tooker** [comment]
PUBLIC_KEY is missing in the config object

**Comment by JMSwag** [comment]
Fixed in 77d874260d0a419d3af522d0f23fce96b96d9058

v2.1.6 includes this fix. 

```
# Run the command below to generate a new client_config.py
$ pyupdater settings --patches
```

**Comment by cbenhagen** [comment]
@JMSwag thanks! https://github.com/JMSwag/PyUpdater/commit/3b1f970c0eab7026a24c0db3bc76daede8a83a93 fixed this.

**Comment by JMSwag** [comment]
@cbenhagen Teamwork makes the dream work!
