### ISSUE TITLE
Issue with UUID on compile?

### ISSUE THREAD

**Issue by domccorm** [Digital-Sapphire/PyUpdater#276]
Not sure why this is happening...I've had pyupdater compile multiple times totally fine...

Here's the error I'm seeing (from step 1):

```
[INFO] PyUpdater 3.1.1
[INFO] Compiling...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 20, in walk_packages
  File "c:\python360564\lib\site-packages\notebook\terminal\__init__.py", line 13, in <module>
    from .handlers import TerminalHandler, TermSocket
  File "c:\python360564\lib\site-packages\notebook\terminal\handlers.py", line 11, in <module>
    from ..base.zmqhandlers import WebSocketMixin
  File "c:\python360564\lib\site-packages\notebook\base\zmqhandlers.py", line 17, in <module>
    from jupyter_client.session import Session
  File "c:\python360564\lib\site-packages\jupyter_client\__init__.py", line 10, in <module>
    from .multikernelmanager import MultiKernelManager, AsyncMultiKernelManager
  File "c:\python360564\lib\site-packages\jupyter_client\multikernelmanager.py", line 7, in <module>
    import uuid
  File "c:\python360564\lib\site-packages\uuid.py", line 138
    if not 0 <= time_low < 1<<32L:
                                ^
SyntaxError: invalid syntax
```

Any help/ideas would be greatly appreciated!

Thanks,
-Doug

**Comment by domccorm** [comment]
I should mention -- I think this might be linked to the module `tqdm `

**Comment by JMSwag** [comment]
@domccorm Would you be able to create a minimal repo that reproduces this issue?
