### ISSUE TITLE
ed25519 and ImportError

### ISSUE THREAD

**Issue by JPFrancoia** [Digital-Sapphire/PyUpdater#39]
Hi,

This morning, I upgraded to python 3.6 (I'm on Archlinux). Even if I always use virtualenvs when I'm coding, I get the following error just by running 'pyupdater' in the virtualenv. Python 3.5.1 is supposed to be used and yesterday, it worked fine.

 ```
pyupdater                                
Traceback (most recent call last):
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/dsdev_utils/helpers.py", line 115, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: '_LazyImport' object has no attribute 'core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/djipey/.local/share/virtualenvs/cb/bin/pyupdater", line 7, in <module>
    from pyupdater.cli import main
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/pyupdater/__init__.py", line 69, in <module>
    PyUpdater = pyupdater.core.PyUpdater
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/dsdev_utils/helpers.py", line 118, in __getattribute__
    self._dsdev_lazy_load()
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/dsdev_utils/helpers.py", line 104, in _dsdev_lazy_load
    self._dsdev_lazy_target = self._dsdev_lazy_loader()
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/pyupdater/__init__.py", line 32, in pyupdater
    import pyupdater.core
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/pyupdater/core.py", line 30, in <module>
    from pyupdater.key_handler.keys import KeyImporter
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/pyupdater/key_handler/keys.py", line 33, in <module>
    import ed25519
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/ed25519/__init__.py", line 1, in <module>
    from .keys import (BadSignatureError, BadPrefixError,
  File "/home/djipey/.local/share/virtualenvs/cb/lib/python3.5/site-packages/ed25519/keys.py", line 3, in <module>
    from . import _ed25519
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
```

This exception is cryptic and I don't really know where to start. Could you give me a hand please ?

**Comment by JPFrancoia** [comment]
Solved here: https://github.com/berdario/pew/issues/132
It wasn't a pyupdater issue.
