### ISSUE TITLE
app_update.extract_restart() give an error

### ISSUE THREAD

**Issue by ccfiel** [Digital-Sapphire/PyUpdater#43]
I got this error after the update is downloaded and this function is the culprit 

> app_update.extract_restart()

 
any idea why?

``` File "pyupdater/client/updates.py", line 515, in extract_restart
  File "pyupdater/client/updates.py", line 609, in _restart
  File "pyupdater/client/updates.py", line 134, in __init__
  File "posixpath.py", line 70, in join
AttributeError: 'NoneType' object has no attribute 'endswith'
Failed to execute script app
```

**Comment by JMSwag** [comment]
@ccfiel I'll try to reproduce. What platform and architecture does this happen on?

**Comment by ccfiel** [comment]
Thanks! @JMSwag its Linux (Ubuntu 16.04) 64 bit. When there is new update and after successful download the error happened. It will not restart the app.

**Comment by JMSwag** [comment]
@ccfiel This should be fixed in master. Please let me know if otherwise.

**Comment by devAtTheBoat** [comment]
Hi! i'm testing Pyupdater and i'm having the exact same error in OSX.

OSX Yosemite 10.10.5
Python 2.7
Pyinstaller 3.2.1
Pyupdater 2.3.0

```
Traceback (most recent call last):
  File "hoveringSombrero.py", line 1119, in update
  File "pyupdater/client/updates.py", line 515, in extract_restart
  File "pyupdater/client/updates.py", line 609, in _restart
  File "pyupdater/client/updates.py", line 134, in __init__
  File "posixpath.py", line 70, in join
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Also I'm having a similar error when upgrading in a Windows environment:

Windows 10
Python 2.7
Pyinstaller 3.2.1
Pyupdater 2.3.0

```
Traceback (most recent call last):
  File "<string>", line 1118, in update
  File "site-packages\pyupdater\client\updates.py", line 580, in extract_overwrite
  File "site-packages\pyupdater\client\updates.py", line 678, in _win_overwrite
  File "site-packages\pyupdater\client\updates.py", line 161, in process
  File "site-packages\pyupdater\client\updates.py", line 185, in _win_overwrite
SystemExit: 0
```

**Comment by JMSwag** [comment]
@vfxBoat For OSX please use PyUpdater v2.3.0. Your traceback refers to [2.2.0](https://github.com/JMSwag/PyUpdater/blob/88532b4ddccfb3c8dead67f562ffffbb3af26fca/pyupdater/client/updates.py#L134). On Windows the main application is supposed to exit, right after the upgrade process begins in a new system process. See [here](https://github.com/JMSwag/PyUpdater/blob/55af174ba98445fd5c865103d24f437584b77b9b/pyupdater/client/updates.py#L184-L185)

**Comment by devAtTheBoat** [comment]
Hi!, I started with pyupdater 2.2.0 and upgraded to 2.3.0, but it seems that the repository wasn't updated. I had to do a `pyupdater clean` and start again, but it didn't fix the error in Windows.

In windows, the main application fails with the error 

```
    File "site-packages\pyupdater\client\updates.py", line 568, in extract_restart
    File "site-packages\pyupdater\client\updates.py", line 690, in _win_overwrite_restart
    File "site-packages\pyupdater\client\updates.py", line 159, in process
    File "site-packages\pyupdater\client\updates.py", line 208, in _win_overwrite_restart
SystemExit: 0
```

And then opens a new window (without closing the first one)

EDIT:
I just found that sys.exit(0) returns a SystemExit exception. So there is no error in windows, just a wrongly catched Exception.

**Comment by JMSwag** [comment]
@vfxBoat I'll get this fixed up or you can submit a PR. See [here](https://docs.python.org/2/library/os.html#os._exit) for the fix.

**Comment by JMSwag** [comment]
@vfxBoat Fixed in the fix-issue-43-2 branch. I'll merge into master once tests pass.

**Comment by JPFrancoia** [comment]
@JMSwag , just to be sure, calling ```extract_overwrite()``` on Windows will close the main app ?

**Comment by JMSwag** [comment]
@JPFrancoia Yes, that is correct.
