### ISSUE TITLE
TypeError: module object is not callable

### ISSUE THREAD

**Issue by JMSwag** [Digital-Sapphire/PyUpdater#52]
[INFO] root 102: PyUpdater 2.3.1
[ERROR] root 112: 'module' object is not callable
[DEBUG] root 113: 'module' object is not callable
Traceback (most recent call last):
  File "/Users/jmswag/.pyenv/versions/3.5.1/envs/batch-engine/lib/python3.5/site-packages/pyupdater/cli/__init__.py", line 104, in main
    _real_main(args)
  File "/Users/jmswag/.pyenv/versions/3.5.1/envs/batch-engine/lib/python3.5/site-packages/pyupdater/cli/__init__.py", line 85, in _real_main
    _dispatch_command(args, pyi_args)
  File "/Users/jmswag/.pyenv/versions/3.5.1/envs/batch-engine/lib/python3.5/site-packages/pyupdater/cli/__init__.py", line 94, in _dispatch_command
    getattr(commands, cmd)(args, pyi_args)
TypeError: 'module' object is not callable

**Comment by JMSwag** [comment]
Fixed in 037197462956f3287d46a0726b9db49b5899264a
