### ISSUE TITLE
Restart/Upgrade Looping

### ISSUE THREAD

**Issue by stampedeboss** [Digital-Sapphire/PyUpdater#65]
2017-04-11 17:09:32,822 - jetPy - INFO - Starting: Version: 0.0.1704-6.4  Build: 0.0.1704-6.4a-69484e29
2017-04-11 17:09:33,006 - alchemy - DEBUG - DB Engine Initialized
2017-04-11 17:10:12,361 - alchemy - DEBUG - TRACE: Save Table Cache File
2017-04-11 17:10:19,151 - alchemy - DEBUG - Base Tables Init Time: : 0:00:46.146000
2017-04-11 17:10:19,187 - jetMain - DEBUG - jetMain:  Imports Complete
2017-04-11 17:10:19,213 - root - DEBUG - Version - 2.3.2
2017-04-11 17:10:19,227 - pyupdater.client - DEBUG - PyUpdater Version 2.3.2
2017-04-11 17:10:19,408 - jetPy - DEBUG - Parsed command line: Namespace(automatedUpdate='Auto', channel=None, daily_log=False, logfile='jetPy.log', loglevel='INFO', profile=True)
2017-04-11 17:10:19,423 - jetPy - DEBUG - __main__: initialized
2017-04-11 17:10:21,487 - pyupdater.client - DEBUG - Setting up directories...
2017-04-11 17:10:21,489 - pyupdater.client - DEBUG - Downloading key file
2017-04-11 17:10:21,489 - pyupdater.client.downloader - DEBUG - Url for request: https://sre-test.it.att.com:8443/jetonline/downloads/jetPy/keys.gz
2017-04-11 17:10:21,489 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sre-test.it.att.com
2017-04-11 17:10:22,875 - urllib3.connectionpool - DEBUG - https://sre-test.it.att.com:8443 "GET /jetonline/downloads/jetPy/keys.gz HTTP/1.1" 200 180
2017-04-11 17:10:22,875 - pyupdater.client.downloader - DEBUG - Resource URL: https://sre-test.it.att.com:8443/jetonline/downloads/jetPy/keys.gz
2017-04-11 17:10:22,875 - pyupdater.client.downloader - DEBUG - Got content length of: 180
2017-04-11 17:10:22,875 - pyupdater.client.downloader - DEBUG - Block size: 358
2017-04-11 17:10:22,875 - pyupdater.client.downloader - DEBUG - {u'status': u'downloading', u'downloaded': 180, u'total': 180, u'percent_complete': u'100.0', u'time': u'--:--'}
2017-04-11 17:10:22,875 - pyupdater.client.downloader - DEBUG - {u'status': u'finished', u'downloaded': 180, u'total': 180, u'percent_complete': u'100.0', u'time': u'00:00'}
2017-04-11 17:10:22,875 - pyupdater.client.downloader - DEBUG - Download Complete
2017-04-11 17:10:22,875 - pyupdater.client.downloader - DEBUG - No hash to verify
2017-04-11 17:10:22,875 - pyupdater.client - DEBUG - Key file download successful
2017-04-11 17:10:22,875 - dsdev_utils.paths - DEBUG - Changing to Directory --> C:\Users\ar380v\AppData\Local\SRE\jetPy
2017-04-11 17:10:22,877 - pyupdater.client - DEBUG - Writing version file to disk
2017-04-11 17:10:22,878 - dsdev_utils.paths - DEBUG - Moving back to Directory --> C:\Users\ar380v\AppData\Local\Temp\_MEI61~1
2017-04-11 17:10:22,881 - pyupdater.client - DEBUG - Key file verified
2017-04-11 17:10:22,881 - pyupdater.client - DEBUG - Loading version file...
2017-04-11 17:10:22,881 - pyupdater.client - DEBUG - Downloading online version file
2017-04-11 17:10:22,881 - pyupdater.client.downloader - DEBUG - Url for request: https://sre-test.it.att.com:8443/jetonline/downloads/jetPy/versions.gz
2017-04-11 17:10:22,881 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sre-test.it.att.com
2017-04-11 17:10:23,204 - urllib3.connectionpool - DEBUG - https://sre-test.it.att.com:8443 "GET /jetonline/downloads/jetPy/versions.gz HTTP/1.1" 200 2196
2017-04-11 17:10:23,206 - pyupdater.client.downloader - DEBUG - Resource URL: https://sre-test.it.att.com:8443/jetonline/downloads/jetPy/versions.gz
2017-04-11 17:10:23,206 - pyupdater.client.downloader - DEBUG - Got content length of: 2196
2017-04-11 17:10:23,206 - pyupdater.client.downloader - DEBUG - Block size: 4390
2017-04-11 17:10:23,206 - pyupdater.client.downloader - DEBUG - {u'status': u'downloading', u'downloaded': 2196, u'total': 2196, u'percent_complete': u'100.0', u'time': u'--:--'}
2017-04-11 17:10:23,206 - pyupdater.client.downloader - DEBUG - {u'status': u'finished', u'downloaded': 2196, u'total': 2196, u'percent_complete': u'100.0', u'time': u'00:00'}
2017-04-11 17:10:23,206 - pyupdater.client.downloader - DEBUG - Download Complete
2017-04-11 17:10:23,206 - pyupdater.client.downloader - DEBUG - No hash to verify
2017-04-11 17:10:23,206 - pyupdater.client - DEBUG - Version file download successful
2017-04-11 17:10:23,206 - dsdev_utils.paths - DEBUG - Changing to Directory --> C:\Users\ar380v\AppData\Local\SRE\jetPy
2017-04-11 17:10:23,207 - pyupdater.client - DEBUG - Writing version file to disk
2017-04-11 17:10:23,207 - dsdev_utils.paths - DEBUG - Moving back to Directory --> C:\Users\ar380v\AppData\Local\Temp\_MEI61~1
2017-04-11 17:10:23,209 - pyupdater.client - DEBUG - Data type: <type 'str'>
2017-04-11 17:10:23,209 - pyupdater.client - DEBUG - Deleting signature from update data
2017-04-11 17:10:23,213 - pyupdater.client - DEBUG - Version file verified
2017-04-11 17:10:23,213 - pyupdater.client - DEBUG - Version Data:
{u'latest': {u'jetPy': {u'alpha': {u'win': u'0.0.1704-7a'}, u'daily': {u'win': u'0.0.1703-24.3d'}}}, u'updates': {u'jetPy': {u'0.0.1703-24.2d': {u'win': {u'file_hash': u'b35059c8437a131038a2723ee19f365e80b039a0a030ab2831f88c670d50514a', u'file_size': 46908130, u'filename': u'jetPy-win-0.0.1703-24.2d.zip'}}, u'0.0.1704-7a': {u'win': {u'file_hash': u'2e91ad05a2d83250d12f71a7129ed8874ff3f1c85ac7873c819c1f758d6fc1c6', u'file_size': 37216989, u'filename': u'jetPy-win-0.0.1704-7a.zip'}}, u'0.0.1704-5a': {u'win': {u'file_hash': u'83c8cf13291ce6aaaea93ece0412852bfcefb0d7ea1d24c3ac216ca4966451bb', u'file_size': 37207614, u'filename': u'jetPy-win-0.0.1704-5a.zip'}}, u'0.0.1703-19d': {u'win': {u'file_hash': u'52e530631eed4283d6c22e7ee2917dc67a1691d88e9cbdaba02312b100f595a9', u'file_size': 47013157, u'filename': u'jetPy-win-0.0.1703-19d.zip'}}, u'0.0.1704-4.4a': {u'win': {u'file_hash': u'8e323baf38ff0a328e0825518ac09569e6a22b1e40077c87fc024ad81e451c29', u'file_size': 36626536, u'filename': u'jetPy-win-0.0.1704-4.4a.zip'}}, u'0.0.1704-6.3a': {u'win': {u'file_hash': u'068c1249e597dd68864468bb02fbcef2e385b5a20ccf24f9ac7aee1927b04103', u'file_size': 37216743, u'filename': u'jetPy-win-0.0.1704-6.3a.zip'}}, u'0.0.1703-19.1d': {u'win': {u'file_hash': u'43ea96ad5562d60ed27c51902df5118d32c4888d76189f8ad4380ea3ffaf13ad', u'file_size': 47013166, u'filename': u'jetPy-win-0.0.1703-19.1d.zip'}}, u'0.0.1704-1.1a': {u'win': {u'file_hash': u'9983ce65b509ba75c12c3bc3459dc9ed655646bd25212ab7b41487fb6995fd4c', u'file_size': 42235625, u'filename': u'jetPy-win-0.0.1704-1.1a.zip'}}, u'0.0.1704-1a': {u'win': {u'file_hash': u'cfb2c59c89a036d3d48c342b57c2e4446c879c3fc5fbc011696e63755f5b7e12', u'file_size': 42233434, u'filename': u'jetPy-win-0.0.1704-1a.zip'}}, u'0.0.1704-4.2a': {u'win': {u'file_hash': u'd78679aa41dc1612d269848fb4dc622c5d4b94f49ef9ae64ac0a101b7add9523', u'file_size': 36626531, u'filename': u'jetPy-win-0.0.1704-4.2a.zip'}}, u'0.0.1703-25.1a': {u'win': {u'file_hash': u'84b9e7c7f6c9a7f840975291cc4fdef6f80bfaa1b2cafe6b7546b768ff5b67e2', u'file_size': 47048882, u'filename': u'jetPy-win-0.0.1703-25.1a.zip'}}, u'0.0.1704-1.2a': {u'win': {u'file_hash': u'9af812fd554e813da423e6802cc478b3f69474f6d006e8a9a85a0307344091c1', u'file_size': 42235629, u'filename': u'jetPy-win-0.0.1704-1.2a.zip'}}, u'0.0.1703-18.2d': {u'win': {u'file_hash': u'd14de6e20afe1246d542d1d73eea43c927d426195347896c95952f72f406fcb1', u'file_size': 43735800, u'filename': u'jetPy-win-0.0.1703-18.2d.zip'}}, u'0.0.1703-24.3d': {u'win': {u'file_hash': u'1f8181975b1705f95b083a7b5678b803bfb261292f89365970f32f3fa3509f24', u'file_size': 46959797, u'filename': u'jetPy-win-0.0.1703-24.3d.zip'}}, u'0.0.1703-24.1d': {u'win': {u'file_hash': u'fce362a0ef3c7afa7efd563a6b755900acf2dede2abe2c20ca88c0b472165b67', u'file_size': 46908350, u'filename': u'jetPy-win-0.0.1703-24.1d.zip'}}, u'0.0.1703-16d': {u'win': {u'file_hash': u'3b4c44f2c5a53e420618253ad4dfcf708fbbd21eb651589ba73e1b46f4f5ba05', u'file_size': 38864720, u'filename': u'jetPy-win-0.0.1703-16d.zip'}}, u'0.0.1703-16.1d': {u'win': {u'file_hash': u'8cc99e233d65dd68ae0d1001192a63516ebf0b0fb55112cef164cb47a6e886bd', u'file_size': 38864724, u'filename': u'jetPy-win-0.0.1703-16.1d.zip'}}, u'0.0.1704-2.1a': {u'win': {u'file_hash': u'697b6d6bebcf21541963b8e5a2a02fcf6fd1601e8611338b8dc78bf8d02aab32', u'file_size': 42236300, u'filename': u'jetPy-win-0.0.1704-2.1a.zip'}}, u'0.0.1703-15.1d': {u'win': {u'file_hash': u'4931d80583e6e4152c50d3fa318da0596150ad82235cfefadf0e32437dad3d6d', u'file_size': 38864471, u'filename': u'jetPy-win-0.0.1703-15.1d.zip'}}, u'0.0.1704-4.1a': {u'win': {u'file_hash': u'6de28820dc2fa877b16246bb3abff02c4ad106faf5f4592a217b8ac3975c9760', u'file_size': 36619183, u'filename': u'jetPy-win-0.0.1704-4.1a.zip'}}, u'0.0.1703-18d': {u'win': {u'file_hash': u'3b13bed1da928dea9e7068ed64c3f8e4e837d655a7779eafa3252d446722dedf', u'file_size': 41171027, u'filename': u'jetPy-win-0.0.1703-18d.zip'}}, u'0.0.1704-4a': {u'win': {u'file_hash': u'be7ef038aa99258f8ef067c2327f2ba3d9689d9d88ce52e99db4dfe80e7958f3', u'file_size': 36619159, u'filename': u'jetPy-win-0.0.1704-4a.zip'}}, u'0.0.1704-2a': {u'win': {u'file_hash': u'a4d042e9db9a26608cc71a14d2da8770b0cf2fbbb2ab7ac85bb14c0f4a122fc9', u'file_size': 42235707, u'filename': u'jetPy-win-0.0.1704-2a.zip'}}, u'0.0.1703-18.1d': {u'win': {u'file_hash': u'37e7c6bf03835dfc6e96ec77d8b464fd264ee4fc3683f4dd388b9a7b5b184837', u'file_size': 41171018, u'filename': u'jetPy-win-0.0.1703-18.1d.zip'}}, u'0.0.1704-6a': {u'win': {u'file_hash': u'7cec724e1c3d669d05c2ee25a51937cbeb9ea1a6ed83710bacefda70e4385af2', u'file_size': 37207522, u'filename': u'jetPy-win-0.0.1704-6a.zip'}}, u'0.0.1704-4.5a': {u'win': {u'file_hash': u'eead20f5faa3392ac2256dc1287868b695bb55a0fb500e2428502156b3767747', u'file_size': 36614888, u'filename': u'jetPy-win-0.0.1704-4.5a.zip'}}, u'0.0.1703-25.2a': {u'win': {u'file_hash': u'939f00da4378365987e17849523686509a9b30c4dd44ad77c2fbf318f33c8f15', u'file_size': 49367272, u'filename': u'jetPy-win-0.0.1703-25.2a.zip'}}, u'0.0.1704-6.2a': {u'win': {u'file_hash': u'c7b9305a9b5d86ca00b4fffd9731a14e3d06e17767295169a32cb8779f336e02', u'file_size': 37207530, u'filename': u'jetPy-win-0.0.1704-6.2a.zip'}}, u'0.0.1704-6.4a': {u'win': {u'file_hash': u'e315bd68500165c5abb7cac6de6a9edd6f51cc7099e88982ae927f2b139ad768', u'file_size': 37217039, u'filename': u'jetPy-win-0.0.1704-6.4a.zip'}}, u'0.0.1703-24d': {u'win': {u'file_hash': u'2f4f9b448e54d8845f9a1bc0cf42de70f1e5c015700ecba6c155d7529a6c0873', u'file_size': 46908351, u'filename': u'jetPy-win-0.0.1703-24d.zip'}}, u'0.0.1703-18.3d': {u'win': {u'file_hash': u'd4b764f6eab4b3558faaee0b7a705f95734de95cb68e4d0f605fb0c2d1dcb5c4', u'file_size': 46138403, u'filename': u'jetPy-win-0.0.1703-18.3d.zip'}}, u'0.0.1704-4.3a': {u'win': {u'file_hash': u'6cccc5de69201886e4797483d4ace86d4d37be5d8394459b6d8b4e6693574d70', u'file_size': 36626530, u'filename': u'jetPy-win-0.0.1704-4.3a.zip'}}, u'0.0.1703-15d': {u'win': {u'file_hash': u'8ff3e6d1a03e5fe4875516085092510307c2cc03cc50c3c58b2468979bb00540', u'file_size': 38864622, u'filename': u'jetPy-win-0.0.1703-15d.zip'}}, u'0.0.1703-25a': {u'win': {u'file_hash': u'615e1cd385cfa3c6cb8a8cbf128677379f4e46e5cfc4e55a6ce0982e7de6adb8', u'file_size': 46959800, u'filename': u'jetPy-win-0.0.1703-25a.zip'}}, u'0.0.1704-6.1a': {u'win': {u'file_hash': u'463f06e58d8b88be63da095632677d66ca448fd3e9f7ee88dd9a5c652ff22ba9', u'file_size': 37207529, u'filename': u'jetPy-win-0.0.1704-6.1a.zip'}}, u'0.0.1703-16.2d': {u'win': {u'file_hash': u'050bfdac3af9bb51ca7e37a8ef13b31494959e561c689a7d3c8d03fe5fa48c0d', u'file_size': 38864731, u'filename': u'jetPy-win-0.0.1703-16.2d.zip'}}, u'0.0.1704-2.2a': {u'win': {u'file_hash': u'6f55688ed081edb09d2cfcdc5b92be45b64f380c1c6c73e4bf05622d2977a707', u'file_size': 42236300, u'filename': u'jetPy-win-0.0.1704-2.2a.zip'}}}}}
2017-04-11 17:10:23,214 - pyupdater.client - DEBUG - Checking for jetPy updates...
2017-04-11 17:10:23,214 - pyupdater.client.updates - DEBUG - Alpha str: 0.0.1704-7a
2017-04-11 17:10:23,216 - pyupdater.client.updates - DEBUG - Highest version: 0.0.1704-7a
2017-04-11 17:10:23,216 - pyupdater.client - DEBUG - Current version: 0.0.1704-6.4a
2017-04-11 17:10:23,216 - pyupdater.client - DEBUG - Latest version: 0.0.1704-7a
2017-04-11 17:10:23,216 - pyupdater.client - DEBUG - Update Needed: True
2017-04-11 17:10:23,216 - pyupdater.client.updates - DEBUG - Alpha str: 0.0.1704-7a
2017-04-11 17:10:23,216 - pyupdater.client.updates - DEBUG - Highest version: 0.0.1704-7a
2017-04-11 17:10:23,216 - pyupdater.client.updates - DEBUG - Filename for jetPy-0.0.1704-6.4a: jetPy-win-0.0.1704-6.4a.zip
2017-04-11 17:10:23,216 - pyupdater.client.updates - DEBUG - Filename for jetPy-0.0.1704-7a: jetPy-win-0.0.1704-7a.zip
2017-04-11 17:10:23,216 - pyupdater.client.updates - DEBUG - Beginning removal of old updates
2017-04-11 17:10:23,216 - pyupdater.package_handler.package - DEBUG - Filename: jetPy-win-0.0.1704-6.4a.zip
2017-04-11 17:10:23,216 - pyupdater.package_handler.package - DEBUG - Directory: C:\Users\ar380v\AppData\Local\SRE\jetPy\update
2017-04-11 17:10:23,217 - pyupdater.package_handler.package - DEBUG - C:\Users\ar380v\AppData\Local\SRE\jetPy\update\jetPy-win-0.0.1704-6.4a.zip does not exist
2017-04-11 17:10:23,217 - pyupdater.package_handler.package - DEBUG - Not an archive format: None
2017-04-11 17:10:23,219 - jetPy - DEBUG - __main__: Upgrade Available
2017-04-11 17:10:23,220 - dsdev_utils.paths - DEBUG - Changing to Directory --> C:\Users\ar380v\AppData\Local\SRE\jetPy\update
2017-04-11 17:10:23,355 - pyupdater.client.downloader - DEBUG - Hash for binary data: 2e91ad05a2d83250d12f71a7129ed8874ff3f1c85ac7873c819c1f758d6fc1c6
2017-04-11 17:10:23,358 - dsdev_utils.paths - DEBUG - Moving back to Directory --> C:\Users\ar380v\AppData\Local\Temp\_MEI61~1
2017-04-11 17:10:23,358 - dsdev_utils.paths - DEBUG - Changing to Directory --> C:\Users\ar380v\AppData\Local\SRE\jetPy\update
2017-04-11 17:10:23,489 - pyupdater.client.downloader - DEBUG - Hash for binary data: 2e91ad05a2d83250d12f71a7129ed8874ff3f1c85ac7873c819c1f758d6fc1c6
2017-04-11 17:10:23,492 - dsdev_utils.paths - DEBUG - Moving back to Directory --> C:\Users\ar380v\AppData\Local\Temp\_MEI61~1
2017-04-11 17:10:23,493 - dsdev_utils.paths - DEBUG - Changing to Directory --> C:\Users\ar380v\AppData\Local\SRE\jetPy\update
2017-04-11 17:10:23,628 - pyupdater.client.downloader - DEBUG - Hash for binary data: 2e91ad05a2d83250d12f71a7129ed8874ff3f1c85ac7873c819c1f758d6fc1c6
2017-04-11 17:10:23,631 - pyupdater.client.updates - DEBUG - Extracting Update
2017-04-11 17:10:23,631 - pyupdater.client.updates - DEBUG - [Errno 13] Permission denied: 'C:\\Users\\ar380v\\AppData\\Local\\SRE\\jetPy\\update\\jetPy.exe'
Traceback (most recent call last):
  File "Lib\site-packages\pyupdater\client\updates.py", line 459, in _extract_update
  File "zipfile.py", line 1043, in extractall
  File "zipfile.py", line 1031, in extract
  File "zipfile.py", line 1086, in _extract_member
IOError: [Errno 13] Permission denied: 'C:\\Users\\ar380v\\AppData\\Local\\SRE\\jetPy\\update\\jetPy.exe'
2017-04-11 17:10:23,631 - dsdev_utils.paths - DEBUG - Moving back to Directory --> C:\Users\ar380v\AppData\Local\Temp\_MEI61~1
2017-04-11 17:10:23,631 - pyupdater.client.updates - DEBUG - Error reading zip file; please report this issue on https://github.com/JMSwag/PyUpdater/issues
Traceback (most recent call last):
  File "Lib\site-packages\pyupdater\client\updates.py", line 568, in extract_restart
  File "Lib\site-packages\pyupdater\client\updates.py", line 462, in _extract_update
ClientError: Error reading zip file; please report this issue on https://github.com/JMSwag/PyUpdater/issues

**Comment by JMSwag** [comment]
@stampedeboss Looks like a permission error. I'll get that log message updated.

**Comment by JMSwag** [comment]
Added in 92ed104e5ade434475ad6fca6e2b415340a01a73
